### PR TITLE
添加数据导入对date、time、datetime类型的支持

### PR DESCRIPTION
**Pull request by git-spower**

### CODE REVIEW

**Comment by jievince** [comment]
Good job! Can you sign in CLAassistant? We can only accept your PR if you have signed in.
image

**Review by yixinglu — COMMENTED** [review]
Could you add some test cases for this PR? you can reference [the example here](https://github.com/vesoft-inc/nebula-importer/tree/master/examples/v2).

**Comment by git-spower** [comment]
is this ok?

**Comment by yixinglu** [comment]
Hi @git-spower 

Sorry to reply late. Firstly, we can only accept you PR only if you sign our CLA. Secondly, please add some test data in our CI in order to verify your changes.

**Comment by yixinglu** [comment]
HI @git-spower 

Could you sign the CLA?

**Review by yixinglu — APPROVED** [review]

**Comment by yixinglu** [comment]
Hi @git-spower Are you there ?

**Comment by yixinglu** [comment]
I will close this PR now since we can not contact to the author. And resubmit a new PR to support this feature.

**Pull request closed without merging**
